export default {
  notfound: "/assets/images/404.svg",
  logo: "/assets/images/logo.png",
  logo_img: "/assets/images/logo_img.png",
  story_img: "/assets/images/story_img.png",
  sliding_heading_icon: "/assets/images/sliding-heading-icon.png",
  vikashJhaPortrait: "/assets/images/vikashJhaPortrait.png",
  sahilBiswasPortrait: "/assets/images/sahilBiswasPortrait.png",
  shashankSinghPortrait: "/assets/images/shashankSinghPortrait.png",
  sayanChoudhuryPortrait: "/assets/images/sayanChoudhuryPortrait.png",
  subheading_icon: "/assets/images/subheading-icon.png",
  web_design: "/assets/images/web-design.png",
  ui_ux: "/assets/images/ui-ux.png",
  branding: "/assets/images/branding.png",
  digital_marketing: "/assets/images/digital-marketing.png",
  mobile_app_dev: "/assets/images/mobile-app-dev.png",
  web_application: "/assets/images/web-application.png",
  ui_ux_ring: "/assets/images/ui-ux-ring.png",
  web_applications_ring: "/assets/images/web-applications-ring.png",
  web_design_ring: "/assets/images/web-design-ring.png",
  branding_block_ring: "/assets/images/branding-block-ring.png",
  digital_marketing_ring: "/assets/images/digital-marketing-ring.png",
  mobile_app_dev_block_bg: "/assets/images/mobile-app-dev-block-bg.png",
  team1: "/assets/images/team-1.jpg",
  why_us_col_img: "/assets/images/why-us-col-img1.png",
  weLyr: "/assets/images/weLyr.png"
};
